mvideo_crawler: # every day at 01:00
  cron: '0 1 * * *'
  class: "Cron::MvideoCrawlWorker"

eldorado_crawler: # every day at 01:30
  cron: '30 1 * * *'
  class: 'Cron::EldoradoCrawlWorker'

dns_crawler: # every day at 02:00
  cron: '0 2 * * *'
  class: 'Cron::DnsCrawlWorker'